# Generated by Django 5.2.1 on 2025-06-17 22:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date_created'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'Savings'), ('CHK', 'Checking'), ('MMA', 'Money Market'), ('CD', 'Certificate of Deposit'), ('IRA', 'Individual Retirement')], default='SAV', max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'Central Africa Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='FCFA', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
