# Generated by Django 5.2.1 on 2025-06-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_num', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=30)),
                ('account_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
